# Business Case Questions
- Q. 1) Show the number of Confirmed, Deaths and Recovered cases in each Region.
- Q. 2) Remove all the records where the Confirmed Cases is Less Than 10.
- Q. 3) In which Region, maximum number of Confirmed cases were recorded ?
- Q. 4) In which Region, minimum number of Deaths cases were recorded ?
- Q. 5) How many Confirmed, Deaths & Recovered cases were reported from India till 29 April 2020 ?
- Q. 6-A ) Sort the entire data wrt No. of Confirmed cases in ascending order.
- Q. 6-B ) Sort the entire data wrt No. of Recovered cases in descending order.

In [1]:
#Importing Required Library
import pandas as pd
import numpy as np

In [2]:
#read the data
df=pd.read_csv(r"C:\Users\Lenovo\Documents\jupyter\DataSets\4. covid_19_data.csv")

In [3]:
df.sample(10)

,Date,State,Region,Confirmed,Deaths,Recovered
237,4/29/2020,Jiangsu,Mainland China,653,0,648
232,4/29/2020,Illinois,US,50358,2215,0
306,4/29/2020,Turks and Caicos Islands,UK,12,1,5
3,4/29/2020,NaN,Andorra,743,42,423
127,4/29/2020,NaN,Paraguay,239,9,102
255,4/29/2020,Montana,US,451,16,0
129,4/29/2020,NaN,Philippines,8212,558,1023
85,4/29/2020,NaN,Kazakhstan,3138,25,819
293,4/29/2020,Shanghai,Mainland China,647,7,597
33,4/29/2020,NaN,Chile,14885,216,8057

In [4]:
pd.set_option("display.max_rows",None)

In [5]:
df.shape

(321, 6)

In [6]:
df.columns

Index(['Date', 'State', 'Region', 'Confirmed', 'Deaths', 'Recovered'], dtype='object')

In [7]:
df.size

1926

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 321 entries, 0 to 320
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       321 non-null    object
 1   State      140 non-null    object
 2   Region     321 non-null    object
 3   Confirmed  321 non-null    int64
 4   Deaths     321 non-null    int64
 5   Recovered  321 non-null    int64
dtypes: int64(3), object(3)
memory usage: 15.2+ KB

In [9]:
df.isnull().sum()

Date           0
State        181
Region         0
Confirmed      0
Deaths         0
Recovered      0
dtype: int64

# Q. 1) Show the number of Confirmed, Deaths and Recovered cases in each Region.

In [10]:
df.groupby('Region')[['Confirmed','Deaths','Recovered']].sum().sort_values(by='Confirmed',ascending=False)

                                  Confirmed  Deaths  Recovered
Region
US                                  1039909   60967     120720
Spain                                236899   24275     132929
Italy                                203591   27682      71252
France                               166543   24121      49118
UK                                   166441   26166        857
Germany                              161539    6467     120400
Turkey                               117589    3081      44040
Russia                                99399     972      10286
Iran                                  93657    5957      73791
Mainland China                        82862    4633      77610
Brazil                                79685    5513      34132
Canada                                52865    3155      20327
Belgium                               47859    7501      11283
Netherlands                           38998    4727        119
Peru                                  33931     943      10037
India                                 33062    1079       8437
Switzerland                           29407    1716      22600
Ecuador                               24675     883       1557
Portugal                              24505     973       1470
Saudi Arabia                          21402     157       2953
Sweden                                20302    2462       1005
Ireland                               20253    1190      13386
Mexico                                17799    1732      11423
Israel                                15834     215       8233
Singapore                             15641      14       1188
Pakistan                              15525     343       3425
Austria                               15402     580      12779
Chile                                 14885     216       8057
Japan                                 13895     413       2368
Belarus                               13181      84       2072
Poland                                12640     624       3025
Qatar                                 12564      10       1243
Romania                               11978     693       3569
United Arab Emirates                  11929      98       2329
South Korea                           10765     247       9059
Ukraine                                9866     250       1103
Indonesia                              9771     784       1391
Denmark                                9206     443       6558
Philippines                            8212     558       1023
Norway                                 7710     207         32
Czech Republic                         7579     227       3108
Bangladesh                             7103     163        150
Australia                              6752      91       5715
Dominican Republic                     6652     293       1228
Serbia                                 6630     125        870
Panama                                 6378     178        527
Colombia                               6207     278       1411
Malaysia                               5945     100       4087
South Africa                           5350     103       2073
Egypt                                  5268     380       1335
Finland                                4906     206       2800
Morocco                                4321     168        928
Argentina                              4285     214       1192
Algeria                                3848     444       1702
Moldova                                3771     111       1114
Luxembourg                             3769      89       3134
Kuwait                                 3740      24       1389
Kazakhstan                             3138      25        819
Thailand                               2947      54       2665
Bahrain                                2921       8       1455
Hungary                                2727     300        536
Greece                                 2576     139        577
Oman                                   2274      10        364
Croatia                                2062      67       1288
Iraq                                   2003      92       1346
Uzbekistan                             2002       9       1096
Afghanistan                            1939      60        252
Armenia                                1932      30        900
Cameroon                               1832      61        934
Iceland                                1797      10       1656
Azerbaijan                             1766      23       1267
Nigeria                                1728      51        307
Bosnia and Herzegovina                 1677      65        710
Ghana                                  1671      16        188
Estonia                                1666      50        236
New Zealand                            1476      19       1241
Cuba                                   1467      58        617
Bulgaria                               1447      64        243
North Macedonia                        1442      73        627
Slovenia                               1418      89        230
Slovakia                               1391      22        484
Lithuania                              1375      45        563
Guinea                                 1351       7        313
Ivory Coast                            1238      14        557
Bolivia                                1110      59        117
Djibouti                               1077       2        599
Hong Kong                              1037       4        830
Tunisia                                 980      40        294
Senegal                                 882       9        315
Latvia                                  849      15        348
Cyprus                                  843      15        148
Albania                                 766      30        455
Andorra                                 743      42        423
Honduras                                738      66         73
Kyrgyzstan                              729       8        437
Lebanon                                 721      24        150
Costa Rica                              713       6        323
Niger                                   713      32        435
Diamond Princess                        712      13        645
Sri Lanka                               649       7        136
Burkina Faso                            641      43        498
Uruguay                                 630      15        412
Somalia                                 582      28         20
San Marino                              563      41         69
Guatemala                               557      16         62
Georgia                                 517       6        178
Kosovo                                  510      12         93
Congo (Kinshasa)                        491      30         59
Mali                                    482      25        129
Tanzania                                480      16        167
Malta                                   463       4        339
Jordan                                  451       8        356
Taiwan                                  429       6        311
Jamaica                                 396       7         29
Kenya                                   384      15        129
El Salvador                             377       9        106
Sudan                                   375      28         32
West Bank and Gaza                      344       2         71
Mauritius                               332      10        306
Venezuela                               331      10        142
Montenegro                              322       7        203
Equatorial Guinea                       315       1          9
Maldives                                278       1         17
Gabon                                   276       3         67
Vietnam                                 270       0        222
Paraguay                                239       9        102
Rwanda                                  225       0         98
Congo (Brazzaville)                     207       8         19
Guinea-Bissau                           205       1         19
Burma                                   150       6         27
Liberia                                 141      16         45
Brunei                                  138       1        124
Ethiopia                                130       3         58
Madagascar                              128       0         90
Cambodia                                122       0        119
Trinidad and Tobago                     116       8         71
Cabo Verde                              114       1          2
Togo                                    109       7         64
Sierra Leone                            104       4         12
Zambia                                   97       3         54
Monaco                                   95       4         58
Eswatini                                 91       1         10
Liechtenstein                            82       1         55
Uganda                                   81       0         52
Barbados                                 80       7         39
Bahamas                                  80      11         23
Guyana                                   78       8         18
Haiti                                    76       6          8
Mozambique                               76       0         12
Benin                                    64       1         33
Libya                                    61       2         18
Nepal                                    57       0         16
Chad                                     52       2         19
Central African Republic                 50       0         10
Macau                                    45       0         34
Syria                                    43       3         21
Eritrea                                  39       0         19
Mongolia                                 38       0         10
Malawi                                   36       3          7
South Sudan                              34       0          0
Zimbabwe                                 32       4          5
Angola                                   27       2          7
Timor-Leste                              24       0          6
Antigua and Barbuda                      24       3         11
Botswana                                 23       1          5
Grenada                                  20       0         13
Laos                                     19       0          7
Belize                                   18       2          9
Fiji                                     18       0         12
Saint Lucia                              17       0         15
Dominica                                 16       0         13
Namibia                                  16       0          8
Saint Vincent and the Grenadines         16       0          8
Saint Kitts and Nevis                    15       0          4
Nicaragua                                13       3          7
Seychelles                               11       0          6
Burundi                                  11       1          4
Suriname                                 10       1          8
Gambia                                   10       1          8
Holy See                                 10       0          2
MS Zaandam                                9       2          0
Mauritania                                8       1          6
Sao Tome and Principe                     8       0          4
Papua New Guinea                          8       0          0
Bhutan                                    7       0          5
Western Sahara                            6       0          5
Yemen                                     6       0          1

In [11]:
df['Region'].nunique()

187

# Q. 2) Remove all the records where the Confirmed Cases is Less Than 10.

In [12]:
df[df['Confirmed']<10]

,Date,State,Region,Confirmed,Deaths,Recovered
18,4/29/2020,NaN,Bhutan,7,0,5
98,4/29/2020,NaN,MS Zaandam,9,2,0
105,4/29/2020,NaN,Mauritania,8,1,6
126,4/29/2020,NaN,Papua New Guinea,8,0,0
140,4/29/2020,NaN,Sao Tome and Principe,8,0,4
177,4/29/2020,NaN,Western Sahara,6,0,5
178,4/29/2020,NaN,Yemen,6,0,1
184,4/29/2020,Anguilla,UK,3,0,3
192,4/29/2020,"Bonaire, Sint Eustatius and Saba",Netherlands,5,0,0
194,4/29/2020,British Virgin Islands,UK,6,1,3
203,4/29/2020,Diamond Princess cruise ship,Canada,0,1,0
272,4/29/2020,Northwest Territories,Canada,5,0,0
284,4/29/2020,Recovered,Canada,0,0,20327
285,4/29/2020,Recovered,US,0,0,120720
288,4/29/2020,Saint Barthelemy,France,6,0,6
289,4/29/2020,Saint Pierre and Miquelon,France,1,0,0
305,4/29/2020,Tibet,Mainland China,1,0,1

In [13]:
df=df.drop(df[df['Confirmed']<10].index)

In [14]:
df

,Date,State,Region,Confirmed,Deaths,Recovered
0,4/29/2020,NaN,Afghanistan,1939,60,252
1,4/29/2020,NaN,Albania,766,30,455
2,4/29/2020,NaN,Algeria,3848,444,1702
3,4/29/2020,NaN,Andorra,743,42,423
4,4/29/2020,NaN,Angola,27,2,7
5,4/29/2020,NaN,Antigua and Barbuda,24,3,11
6,4/29/2020,NaN,Argentina,4285,214,1192
7,4/29/2020,NaN,Armenia,1932,30,900
8,4/29/2020,NaN,Austria,15402,580,12779
9,4/29/2020,NaN,Azerbaijan,1766,23,1267
10,4/29/2020,NaN,Bahamas,80,11,23
11,4/29/2020,NaN,Bahrain,2921,8,1455
12,4/29/2020,NaN,Bangladesh,7103,163,150
13,4/29/2020,NaN,Barbados,80,7,39
14,4/29/2020,NaN,Belarus,13181,84,2072
15,4/29/2020,NaN,Belgium,47859,7501,11283
16,4/29/2020,NaN,Belize,18,2,9
17,4/29/2020,NaN,Benin,64,1,33
19,4/29/2020,NaN,Bolivia,1110,59,117
20,4/29/2020,NaN,Bosnia and Herzegovina,1677,65,710
21,4/29/2020,NaN,Botswana,23,1,5
22,4/29/2020,NaN,Brazil,79685,5513,34132
23,4/29/2020,NaN,Brunei,138,1,124
24,4/29/2020,NaN,Bulgaria,1447,64,243
25,4/29/2020,NaN,Burkina Faso,641,43,498
26,4/29/2020,NaN,Burma,150,6,27
27,4/29/2020,NaN,Burundi,11,1,4
28,4/29/2020,NaN,Cabo Verde,114,1,2
29,4/29/2020,NaN,Cambodia,122,0,119
30,4/29/2020,NaN,Cameroon,1832,61,934
31,4/29/2020,NaN,Central African Republic,50,0,10
32,4/29/2020,NaN,Chad,52,2,19
33,4/29/2020,NaN,Chile,14885,216,8057
34,4/29/2020,NaN,Colombia,6207,278,1411
35,4/29/2020,NaN,Congo (Brazzaville),207,8,19
36,4/29/2020,NaN,Congo (Kinshasa),491,30,59
37,4/29/2020,NaN,Costa Rica,713,6,323
38,4/29/2020,NaN,Croatia,2062,67,1288
39,4/29/2020,NaN,Cuba,1467,58,617
40,4/29/2020,NaN,Cyprus,843,15,148
41,4/29/2020,NaN,Czech Republic,7579,227,3108
42,4/29/2020,NaN,Denmark,9008,443,6366
43,4/29/2020,NaN,Diamond Princess,712,13,645
44,4/29/2020,NaN,Djibouti,1077,2,599
45,4/29/2020,NaN,Dominica,16,0,13
46,4/29/2020,NaN,Dominican Republic,6652,293,1228
47,4/29/2020,NaN,Ecuador,24675,883,1557
48,4/29/2020,NaN,Egypt,5268,380,1335
49,4/29/2020,NaN,El Salvador,377,9,106
50,4/29/2020,NaN,Equatorial Guinea,315,1,9
51,4/29/2020,NaN,Eritrea,39,0,19
52,4/29/2020,NaN,Estonia,1666,50,236
53,4/29/2020,NaN,Eswatini,91,1,10
54,4/29/2020,NaN,Ethiopia,130,3,58
55,4/29/2020,NaN,Fiji,18,0,12
56,4/29/2020,NaN,Finland,4906,206,2800
57,4/29/2020,NaN,France,165093,24087,48228
58,4/29/2020,NaN,Gabon,276,3,67
59,4/29/2020,NaN,Gambia,10,1,8
60,4/29/2020,NaN,Georgia,517,6,178
61,4/29/2020,NaN,Germany,161539,6467,120400
62,4/29/2020,NaN,Ghana,1671,16,188
63,4/29/2020,NaN,Greece,2576,139,577
64,4/29/2020,NaN,Grenada,20,0,13
65,4/29/2020,NaN,Guatemala,557,16,62
66,4/29/2020,NaN,Guinea,1351,7,313
67,4/29/2020,NaN,Guinea-Bissau,205,1,19
68,4/29/2020,NaN,Guyana,78,8,18
69,4/29/2020,NaN,Haiti,76,6,8
70,4/29/2020,NaN,Holy See,10,0,2
71,4/29/2020,NaN,Honduras,738,66,73
72,4/29/2020,NaN,Hungary,2727,300,536
73,4/29/2020,NaN,Iceland,1797,10,1656
74,4/29/2020,NaN,India,33062,1079,8437
75,4/29/2020,NaN,Indonesia,9771,784,1391
76,4/29/2020,NaN,Iran,93657,5957,73791
77,4/29/2020,NaN,Iraq,2003,92,1346
78,4/29/2020,NaN,Ireland,20253,1190,13386
79,4/29/2020,NaN,Israel,15834,215,8233
80,4/29/2020,NaN,Italy,203591,27682,71252
81,4/29/2020,NaN,Ivory Coast,1238,14,557
82,4/29/2020,NaN,Jamaica,396,7,29
83,4/29/2020,NaN,Japan,13895,413,2368
84,4/29/2020,NaN,Jordan,451,8,356
85,4/29/2020,NaN,Kazakhstan,3138,25,819
86,4/29/2020,NaN,Kenya,384,15,129
87,4/29/2020,NaN,Kosovo,510,12,93
88,4/29/2020,NaN,Kuwait,3740,24,1389
89,4/29/2020,NaN,Kyrgyzstan,729,8,437
90,4/29/2020,NaN,Laos,19,0,7
91,4/29/2020,NaN,Latvia,849,15,348
92,4/29/2020,NaN,Lebanon,721,24,150
93,4/29/2020,NaN,Liberia,141,16,45
94,4/29/2020,NaN,Libya,61,2,18
95,4/29/2020,NaN,Liechtenstein,82,1,55
96,4/29/2020,NaN,Lithuania,1375,45,563
97,4/29/2020,NaN,Luxembourg,3769,89,3134
99,4/29/2020,NaN,Madagascar,128,0,90
100,4/29/2020,NaN,Malawi,36,3,7
101,4/29/2020,NaN,Malaysia,5945,100,4087
102,4/29/2020,NaN,Maldives,278,1,17
103,4/29/2020,NaN,Mali,482,25,129
104,4/29/2020,NaN,Malta,463,4,339
106,4/29/2020,NaN,Mauritius,332,10,306
107,4/29/2020,NaN,Mexico,17799,1732,11423
108,4/29/2020,NaN,Moldova,3771,111,1114
109,4/29/2020,NaN,Monaco,95,4,58
110,4/29/2020,NaN,Mongolia,38,0,10
111,4/29/2020,NaN,Montenegro,322,7,203
112,4/29/2020,NaN,Morocco,4321,168,928
113,4/29/2020,NaN,Mozambique,76,0,12
114,4/29/2020,NaN,Namibia,16,0,8
115,4/29/2020,NaN,Nepal,57,0,16
116,4/29/2020,NaN,Netherlands,38802,4711,0
117,4/29/2020,NaN,New Zealand,1476,19,1241
118,4/29/2020,NaN,Nicaragua,13,3,7
119,4/29/2020,NaN,Niger,713,32,435
120,4/29/2020,NaN,Nigeria,1728,51,307
121,4/29/2020,NaN,North Macedonia,1442,73,627
122,4/29/2020,NaN,Norway,7710,207,32
123,4/29/2020,NaN,Oman,2274,10,364
124,4/29/2020,NaN,Pakistan,15525,343,3425
125,4/29/2020,NaN,Panama,6378,178,527
127,4/29/2020,NaN,Paraguay,239,9,102
128,4/29/2020,NaN,Peru,33931,943,10037
129,4/29/2020,NaN,Philippines,8212,558,1023
130,4/29/2020,NaN,Poland,12640,624,3025
131,4/29/2020,NaN,Portugal,24505,973,1470
132,4/29/2020,NaN,Qatar,12564,10,1243
133,4/29/2020,NaN,Romania,11978,693,3569
134,4/29/2020,NaN,Russia,99399,972,10286
135,4/29/2020,NaN,Rwanda,225,0,98
136,4/29/2020,NaN,Saint Kitts and Nevis,15,0,4
137,4/29/2020,NaN,Saint Lucia,17,0,15
138,4/29/2020,NaN,Saint Vincent and the Grenadines,16,0,8
139,4/29/2020,NaN,San Marino,563,41,69
141,4/29/2020,NaN,Saudi Arabia,21402,157,2953
142,4/29/2020,NaN,Senegal,882,9,315
143,4/29/2020,NaN,Serbia,6630,125,870
144,4/29/2020,NaN,Seychelles,11,0,6
145,4/29/2020,NaN,Sierra Leone,104,4,12
146,4/29/2020,NaN,Singapore,15641,14,1188
147,4/29/2020,NaN,Slovakia,1391,22,484
148,4/29/2020,NaN,Slovenia,1418,89,230
149,4/29/2020,NaN,Somalia,582,28,20
150,4/29/2020,NaN,South Africa,5350,103,2073
151,4/29/2020,NaN,South Korea,10765,247,9059
152,4/29/2020,NaN,South Sudan,34,0,0
153,4/29/2020,NaN,Spain,236899,24275,132929
154,4/29/2020,NaN,Sri Lanka,649,7,136
155,4/29/2020,NaN,Sudan,375,28,32
156,4/29/2020,NaN,Suriname,10,1,8
157,4/29/2020,NaN,Sweden,20302,2462,1005
158,4/29/2020,NaN,Switzerland,29407,1716,22600
159,4/29/2020,NaN,Syria,43,3,21
160,4/29/2020,NaN,Taiwan,429,6,311
161,4/29/2020,NaN,Tanzania,480,16,167
162,4/29/2020,NaN,Thailand,2947,54,2665
163,4/29/2020,NaN,Timor-Leste,24,0,6
164,4/29/2020,NaN,Togo,109,7,64
165,4/29/2020,NaN,Trinidad and Tobago,116,8,71
166,4/29/2020,NaN,Tunisia,980,40,294
167,4/29/2020,NaN,Turkey,117589,3081,44040
168,4/29/2020,NaN,UK,165221,26097,0
169,4/29/2020,NaN,Uganda,81,0,52
170,4/29/2020,NaN,Ukraine,9866,250,1103
171,4/29/2020,NaN,United Arab Emirates,11929,98,2329
172,4/29/2020,NaN,Uruguay,630,15,412
173,4/29/2020,NaN,Uzbekistan,2002,9,1096
174,4/29/2020,NaN,Venezuela,331,10,142
175,4/29/2020,NaN,Vietnam,270,0,222
176,4/29/2020,NaN,West Bank and Gaza,344,2,71
179,4/29/2020,NaN,Zambia,97,3,54
180,4/29/2020,NaN,Zimbabwe,32,4,5
181,4/29/2020,Alabama,US,6912,256,0
182,4/29/2020,Alaska,US,355,9,0
183,4/29/2020,Alberta,Canada,5165,87,0
185,4/29/2020,Anhui,Mainland China,991,6,985
186,4/29/2020,Arizona,US,7209,308,0
187,4/29/2020,Arkansas,US,3193,57,0
188,4/29/2020,Aruba,Netherlands,100,2,73
189,4/29/2020,Australian Capital Territory,Australia,106,3,101
190,4/29/2020,Beijing,Mainland China,593,9,542
191,4/29/2020,Bermuda,UK,111,6,48
193,4/29/2020,British Columbia,Canada,2087,109,0
195,4/29/2020,California,US,48747,1946,0
196,4/29/2020,Cayman Islands,UK,73,1,10
197,4/29/2020,Channel Islands,UK,537,38,386
198,4/29/2020,Chongqing,Mainland China,579,6,573
199,4/29/2020,Colorado,US,14758,766,0
200,4/29/2020,Connecticut,US,26767,2169,0
201,4/29/2020,Curacao,Netherlands,16,1,13
202,4/29/2020,Delaware,US,4655,144,0
204,4/29/2020,Diamond Princess cruise ship,US,49,0,0
205,4/29/2020,District of Columbia,US,4106,205,0
206,4/29/2020,Falkland Islands (Malvinas),UK,13,0,11
207,4/29/2020,Faroe Islands,Denmark,187,0,181
208,4/29/2020,Florida,US,33193,1218,0
209,4/29/2020,French Guiana,France,125,1,93
210,4/29/2020,French Polynesia,France,58,0,50
211,4/29/2020,Fujian,Mainland China,355,1,353
212,4/29/2020,Gansu,Mainland China,139,2,137
213,4/29/2020,Georgia,US,25775,1101,0
214,4/29/2020,Gibraltar,UK,141,0,131
215,4/29/2020,Grand Princess,Canada,13,0,0
216,4/29/2020,Grand Princess,US,103,3,0
217,4/29/2020,Greenland,Denmark,11,0,11
218,4/29/2020,Guadeloupe,France,149,12,82
219,4/29/2020,Guam,US,141,5,0
220,4/29/2020,Guangdong,Mainland China,1588,8,1557
221,4/29/2020,Guangxi,Mainland China,254,2,252
222,4/29/2020,Guizhou,Mainland China,147,2,145
223,4/29/2020,Hainan,Mainland China,168,6,162
224,4/29/2020,Hawaii,US,613,16,0
225,4/29/2020,Hebei,Mainland China,328,6,318
226,4/29/2020,Heilongjiang,Mainland China,939,13,587
227,4/29/2020,Henan,Mainland China,1276,22,1254
228,4/29/2020,Hong Kong,Hong Kong,1037,4,830
229,4/29/2020,Hubei,Mainland China,68128,4512,63616
230,4/29/2020,Hunan,Mainland China,1019,4,1015
231,4/29/2020,Idaho,US,1952,60,0
232,4/29/2020,Illinois,US,50358,2215,0
233,4/29/2020,Indiana,US,17182,964,0
234,4/29/2020,Inner Mongolia,Mainland China,200,1,150
235,4/29/2020,Iowa,US,6843,148,0
236,4/29/2020,Isle of Man,UK,313,21,258
237,4/29/2020,Jiangsu,Mainland China,653,0,648
238,4/29/2020,Jiangxi,Mainland China,937,1,936
239,4/29/2020,Jilin,Mainland China,111,1,99
240,4/29/2020,Kansas,US,3839,134,0
241,4/29/2020,Kentucky,US,4537,234,0
242,4/29/2020,Liaoning,Mainland China,146,2,143
243,4/29/2020,Louisiana,US,27660,1845,0
244,4/29/2020,Macau,Macau,45,0,34
245,4/29/2020,Maine,US,1056,52,0
246,4/29/2020,Manitoba,Canada,275,6,0
247,4/29/2020,Martinique,France,175,14,83
248,4/29/2020,Maryland,US,20849,1078,0
249,4/29/2020,Massachusetts,US,60265,3405,0
250,4/29/2020,Mayotte,France,460,4,235
251,4/29/2020,Michigan,US,40399,3670,0
252,4/29/2020,Minnesota,US,4644,319,0
253,4/29/2020,Mississippi,US,6569,250,0
254,4/29/2020,Missouri,US,7660,338,0
255,4/29/2020,Montana,US,451,16,0
256,4/29/2020,Montserrat,UK,11,1,2
257,4/29/2020,Nebraska,US,3851,56,0
258,4/29/2020,Nevada,US,4934,230,0
259,4/29/2020,New Brunswick,Canada,118,0,0
260,4/29/2020,New Caledonia,France,18,0,17
261,4/29/2020,New Hampshire,US,2058,60,0
262,4/29/2020,New Jersey,US,116365,6771,0
263,4/29/2020,New Mexico,US,3213,112,0
264,4/29/2020,New South Wales,Australia,3016,40,2284
265,4/29/2020,New York,US,299691,23477,0
266,4/29/2020,Newfoundland and Labrador,Canada,258,3,0
267,4/29/2020,Ningxia,Mainland China,75,0,75
268,4/29/2020,North Carolina,US,10180,382,0
269,4/29/2020,North Dakota,US,1033,19,0
270,4/29/2020,Northern Mariana Islands,US,14,2,0
271,4/29/2020,Northern Territory,Australia,28,0,25
273,4/29/2020,Nova Scotia,Canada,935,28,0
274,4/29/2020,Ohio,US,17303,937,0
275,4/29/2020,Oklahoma,US,3473,214,0
276,4/29/2020,Ontario,Canada,16978,1153,0
277,4/29/2020,Oregon,US,2446,101,0
278,4/29/2020,Pennsylvania,US,46327,2373,0
279,4/29/2020,Prince Edward Island,Canada,27,0,0
280,4/29/2020,Puerto Rico,US,1433,86,0
281,4/29/2020,Qinghai,Mainland China,18,0,18
282,4/29/2020,Quebec,Canada,26610,1762,0
283,4/29/2020,Queensland,Australia,1033,6,943
286,4/29/2020,Reunion,France,420,0,300
287,4/29/2020,Rhode Island,US,8247,251,0
290,4/29/2020,Saskatchewan,Canada,383,6,0
291,4/29/2020,Shaanxi,Mainland China,306,3,253
292,4/29/2020,Shandong,Mainland China,787,7,772
293,4/29/2020,Shanghai,Mainland China,647,7,597
294,4/29/2020,Shanxi,Mainland China,197,0,164
295,4/29/2020,Sichuan,Mainland China,561,3,558
296,4/29/2020,Sint Maarten,Netherlands,75,13,33
297,4/29/2020,South Australia,Australia,438,4,420
298,4/29/2020,South Carolina,US,5882,231,0
299,4/29/2020,South Dakota,US,2373,13,0
300,4/29/2020,St Martin,France,38,3,24
301,4/29/2020,Tasmania,Australia,219,12,144
302,4/29/2020,Tennessee,US,10366,195,0
303,4/29/2020,Texas,US,27257,754,0
304,4/29/2020,Tianjin,Mainland China,190,3,183
306,4/29/2020,Turks and Caicos Islands,UK,12,1,5
307,4/29/2020,Utah,US,4497,45,0
308,4/29/2020,Vermont,US,862,47,0
309,4/29/2020,Victoria,Australia,1361,18,1291
310,4/29/2020,Virgin Islands,US,57,4,0
311,4/29/2020,Virginia,US,14962,522,0
312,4/29/2020,Washington,US,14070,801,0
313,4/29/2020,West Virginia,US,1110,38,0
314,4/29/2020,Western Australia,Australia,551,8,507
315,4/29/2020,Wisconsin,US,6520,308,0
316,4/29/2020,Wyoming,US,545,7,0
317,4/29/2020,Xinjiang,Mainland China,76,3,73
318,4/29/2020,Yukon,Canada,11,0,0
319,4/29/2020,Yunnan,Mainland China,185,2,181
320,4/29/2020,Zhejiang,Mainland China,1268,1,1263

# Q. 3) In which Region, maximum number of Confirmed cases were recorded ?

In [15]:
df.groupby('Region')[['Confirmed']].sum().sort_values(by='Confirmed',ascending=False)

                                  Confirmed
Region
US                                  1039909
Spain                                236899
Italy                                203591
France                               166536
UK                                   166432
Germany                              161539
Turkey                               117589
Russia                                99399
Iran                                  93657
Mainland China                        82861
Brazil                                79685
Canada                                52860
Belgium                               47859
Netherlands                           38993
Peru                                  33931
India                                 33062
Switzerland                           29407
Ecuador                               24675
Portugal                              24505
Saudi Arabia                          21402
Sweden                                20302
Ireland                               20253
Mexico                                17799
Israel                                15834
Singapore                             15641
Pakistan                              15525
Austria                               15402
Chile                                 14885
Japan                                 13895
Belarus                               13181
Poland                                12640
Qatar                                 12564
Romania                               11978
United Arab Emirates                  11929
South Korea                           10765
Ukraine                                9866
Indonesia                              9771
Denmark                                9206
Philippines                            8212
Norway                                 7710
Czech Republic                         7579
Bangladesh                             7103
Australia                              6752
Dominican Republic                     6652
Serbia                                 6630
Panama                                 6378
Colombia                               6207
Malaysia                               5945
South Africa                           5350
Egypt                                  5268
Finland                                4906
Morocco                                4321
Argentina                              4285
Algeria                                3848
Moldova                                3771
Luxembourg                             3769
Kuwait                                 3740
Kazakhstan                             3138
Thailand                               2947
Bahrain                                2921
Hungary                                2727
Greece                                 2576
Oman                                   2274
Croatia                                2062
Iraq                                   2003
Uzbekistan                             2002
Afghanistan                            1939
Armenia                                1932
Cameroon                               1832
Iceland                                1797
Azerbaijan                             1766
Nigeria                                1728
Bosnia and Herzegovina                 1677
Ghana                                  1671
Estonia                                1666
New Zealand                            1476
Cuba                                   1467
Bulgaria                               1447
North Macedonia                        1442
Slovenia                               1418
Slovakia                               1391
Lithuania                              1375
Guinea                                 1351
Ivory Coast                            1238
Bolivia                                1110
Djibouti                               1077
Hong Kong                              1037
Tunisia                                 980
Senegal                                 882
Latvia                                  849
Cyprus                                  843
Albania                                 766
Andorra                                 743
Honduras                                738
Kyrgyzstan                              729
Lebanon                                 721
Costa Rica                              713
Niger                                   713
Diamond Princess                        712
Sri Lanka                               649
Burkina Faso                            641
Uruguay                                 630
Somalia                                 582
San Marino                              563
Guatemala                               557
Georgia                                 517
Kosovo                                  510
Congo (Kinshasa)                        491
Mali                                    482
Tanzania                                480
Malta                                   463
Jordan                                  451
Taiwan                                  429
Jamaica                                 396
Kenya                                   384
El Salvador                             377
Sudan                                   375
West Bank and Gaza                      344
Mauritius                               332
Venezuela                               331
Montenegro                              322
Equatorial Guinea                       315
Maldives                                278
Gabon                                   276
Vietnam                                 270
Paraguay                                239
Rwanda                                  225
Congo (Brazzaville)                     207
Guinea-Bissau                           205
Burma                                   150
Liberia                                 141
Brunei                                  138
Ethiopia                                130
Madagascar                              128
Cambodia                                122
Trinidad and Tobago                     116
Cabo Verde                              114
Togo                                    109
Sierra Leone                            104
Zambia                                   97
Monaco                                   95
Eswatini                                 91
Liechtenstein                            82
Uganda                                   81
Bahamas                                  80
Barbados                                 80
Guyana                                   78
Haiti                                    76
Mozambique                               76
Benin                                    64
Libya                                    61
Nepal                                    57
Chad                                     52
Central African Republic                 50
Macau                                    45
Syria                                    43
Eritrea                                  39
Mongolia                                 38
Malawi                                   36
South Sudan                              34
Zimbabwe                                 32
Angola                                   27
Antigua and Barbuda                      24
Timor-Leste                              24
Botswana                                 23
Grenada                                  20
Laos                                     19
Fiji                                     18
Belize                                   18
Saint Lucia                              17
Saint Vincent and the Grenadines         16
Namibia                                  16
Dominica                                 16
Saint Kitts and Nevis                    15
Nicaragua                                13
Seychelles                               11
Burundi                                  11
Suriname                                 10
Gambia                                   10
Holy See                                 10

# Q. 4) In which Region, minimum number of Deaths cases were recorded ?

In [19]:
df.groupby('Region')[['Deaths']].sum().sort_values(by='Deaths')

                                  Deaths
Region
Cambodia                               0
Seychelles                             0
Saint Lucia                            0
Central African Republic               0
Saint Kitts and Nevis                  0
South Sudan                            0
Rwanda                                 0
Grenada                                0
Macau                                  0
Madagascar                             0
Nepal                                  0
Namibia                                0
Saint Vincent and the Grenadines       0
Mozambique                             0
Holy See                               0
Timor-Leste                            0
Mongolia                               0
Uganda                                 0
Laos                                   0
Eritrea                                0
Vietnam                                0
Fiji                                   0
Dominica                               0
Gambia                                 1
Equatorial Guinea                      1
Eswatini                               1
Cabo Verde                             1
Maldives                               1
Guinea-Bissau                          1
Liechtenstein                          1
Brunei                                 1
Burundi                                1
Botswana                               1
Suriname                               1
Benin                                  1
Djibouti                               2
Angola                                 2
Libya                                  2
Chad                                   2
West Bank and Gaza                     2
Belize                                 2
Zambia                                 3
Malawi                                 3
Nicaragua                              3
Syria                                  3
Ethiopia                               3
Antigua and Barbuda                    3
Gabon                                  3
Hong Kong                              4
Zimbabwe                               4
Sierra Leone                           4
Malta                                  4
Monaco                                 4
Georgia                                6
Haiti                                  6
Taiwan                                 6
Costa Rica                             6
Burma                                  6
Guinea                                 7
Jamaica                                7
Montenegro                             7
Sri Lanka                              7
Barbados                               7
Togo                                   7
Guyana                                 8
Kyrgyzstan                             8
Jordan                                 8
Congo (Brazzaville)                    8
Trinidad and Tobago                    8
Bahrain                                8
Uzbekistan                             9
El Salvador                            9
Senegal                                9
Paraguay                               9
Mauritius                             10
Qatar                                 10
Iceland                               10
Oman                                  10
Venezuela                             10
Bahamas                               11
Kosovo                                12
Diamond Princess                      13
Ivory Coast                           14
Singapore                             14
Kenya                                 15
Uruguay                               15
Latvia                                15
Cyprus                                15
Tanzania                              16
Ghana                                 16
Guatemala                             16
Liberia                               16
New Zealand                           19
Slovakia                              22
Azerbaijan                            23
Lebanon                               24
Kuwait                                24
Kazakhstan                            25
Mali                                  25
Sudan                                 28
Somalia                               28
Congo (Kinshasa)                      30
Albania                               30
Armenia                               30
Niger                                 32
Tunisia                               40
San Marino                            41
Andorra                               42
Burkina Faso                          43
Lithuania                             45
Estonia                               50
Nigeria                               51
Thailand                              54
Cuba                                  58
Bolivia                               59
Afghanistan                           60
Cameroon                              61
Bulgaria                              64
Bosnia and Herzegovina                65
Honduras                              66
Croatia                               67
North Macedonia                       73
Belarus                               84
Slovenia                              89
Luxembourg                            89
Australia                             91
Iraq                                  92
United Arab Emirates                  98
Malaysia                             100
South Africa                         103
Moldova                              111
Serbia                               125
Greece                               139
Saudi Arabia                         157
Bangladesh                           163
Morocco                              168
Panama                               178
Finland                              206
Norway                               207
Argentina                            214
Israel                               215
Chile                                216
Czech Republic                       227
South Korea                          247
Ukraine                              250
Colombia                             278
Dominican Republic                   293
Hungary                              300
Pakistan                             343
Egypt                                380
Japan                                413
Denmark                              443
Algeria                              444
Philippines                          558
Austria                              580
Poland                               624
Romania                              693
Indonesia                            784
Ecuador                              883
Peru                                 943
Russia                               972
Portugal                             973
India                               1079
Ireland                             1190
Switzerland                         1716
Mexico                              1732
Sweden                              2462
Turkey                              3081
Canada                              3154
Mainland China                      4633
Netherlands                         4727
Brazil                              5513
Iran                                5957
Germany                             6467
Belgium                             7501
France                             24121
Spain                              24275
UK                                 26165
Italy                              27682
US                                 60967

# Q. 5) How many Confirmed, Deaths & Recovered cases were reported from India till 29 April 2020 ?

In [20]:
df['Date']=pd.to_datetime(df['Date'])

In [21]:
df[(df['Region']=='India')&(df['Date']<='29-04-2020')]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_11848\3108673784.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df[(df['Region']=='India')&(df['Date']<='29-04-2020')]

         Date State Region  Confirmed  Deaths  Recovered
74 2020-04-29   NaN  India      33062    1079       8437

# Q. 6-A ) Sort the entire data wrt No. of Confirmed cases in ascending order.

In [24]:
df.sort_values(by='Confirmed',ascending=True)

,Date,State,Region,Confirmed,Deaths,Recovered
156,2020-04-29,NaN,Suriname,10,1,8
70,2020-04-29,NaN,Holy See,10,0,2
59,2020-04-29,NaN,Gambia,10,1,8
318,2020-04-29,Yukon,Canada,11,0,0
217,2020-04-29,Greenland,Denmark,11,0,11
256,2020-04-29,Montserrat,UK,11,1,2
144,2020-04-29,NaN,Seychelles,11,0,6
27,2020-04-29,NaN,Burundi,11,1,4
306,2020-04-29,Turks and Caicos Islands,UK,12,1,5
118,2020-04-29,NaN,Nicaragua,13,3,7
215,2020-04-29,Grand Princess,Canada,13,0,0
206,2020-04-29,Falkland Islands (Malvinas),UK,13,0,11
270,2020-04-29,Northern Mariana Islands,US,14,2,0
136,2020-04-29,NaN,Saint Kitts and Nevis,15,0,4
138,2020-04-29,NaN,Saint Vincent and the Grenadines,16,0,8
45,2020-04-29,NaN,Dominica,16,0,13
201,2020-04-29,Curacao,Netherlands,16,1,13
114,2020-04-29,NaN,Namibia,16,0,8
137,2020-04-29,NaN,Saint Lucia,17,0,15
260,2020-04-29,New Caledonia,France,18,0,17
16,2020-04-29,NaN,Belize,18,2,9
55,2020-04-29,NaN,Fiji,18,0,12
281,2020-04-29,Qinghai,Mainland China,18,0,18
90,2020-04-29,NaN,Laos,19,0,7
64,2020-04-29,NaN,Grenada,20,0,13
21,2020-04-29,NaN,Botswana,23,1,5
5,2020-04-29,NaN,Antigua and Barbuda,24,3,11
163,2020-04-29,NaN,Timor-Leste,24,0,6
279,2020-04-29,Prince Edward Island,Canada,27,0,0
4,2020-04-29,NaN,Angola,27,2,7
271,2020-04-29,Northern Territory,Australia,28,0,25
180,2020-04-29,NaN,Zimbabwe,32,4,5
152,2020-04-29,NaN,South Sudan,34,0,0
100,2020-04-29,NaN,Malawi,36,3,7
300,2020-04-29,St Martin,France,38,3,24
110,2020-04-29,NaN,Mongolia,38,0,10
51,2020-04-29,NaN,Eritrea,39,0,19
159,2020-04-29,NaN,Syria,43,3,21
244,2020-04-29,Macau,Macau,45,0,34
204,2020-04-29,Diamond Princess cruise ship,US,49,0,0
31,2020-04-29,NaN,Central African Republic,50,0,10
32,2020-04-29,NaN,Chad,52,2,19
310,2020-04-29,Virgin Islands,US,57,4,0
115,2020-04-29,NaN,Nepal,57,0,16
210,2020-04-29,French Polynesia,France,58,0,50
94,2020-04-29,NaN,Libya,61,2,18
17,2020-04-29,NaN,Benin,64,1,33
196,2020-04-29,Cayman Islands,UK,73,1,10
296,2020-04-29,Sint Maarten,Netherlands,75,13,33
267,2020-04-29,Ningxia,Mainland China,75,0,75
317,2020-04-29,Xinjiang,Mainland China,76,3,73
113,2020-04-29,NaN,Mozambique,76,0,12
69,2020-04-29,NaN,Haiti,76,6,8
68,2020-04-29,NaN,Guyana,78,8,18
13,2020-04-29,NaN,Barbados,80,7,39
10,2020-04-29,NaN,Bahamas,80,11,23
169,2020-04-29,NaN,Uganda,81,0,52
95,2020-04-29,NaN,Liechtenstein,82,1,55
53,2020-04-29,NaN,Eswatini,91,1,10
109,2020-04-29,NaN,Monaco,95,4,58
179,2020-04-29,NaN,Zambia,97,3,54
188,2020-04-29,Aruba,Netherlands,100,2,73
216,2020-04-29,Grand Princess,US,103,3,0
145,2020-04-29,NaN,Sierra Leone,104,4,12
189,2020-04-29,Australian Capital Territory,Australia,106,3,101
164,2020-04-29,NaN,Togo,109,7,64
239,2020-04-29,Jilin,Mainland China,111,1,99
191,2020-04-29,Bermuda,UK,111,6,48
28,2020-04-29,NaN,Cabo Verde,114,1,2
165,2020-04-29,NaN,Trinidad and Tobago,116,8,71
259,2020-04-29,New Brunswick,Canada,118,0,0
29,2020-04-29,NaN,Cambodia,122,0,119
209,2020-04-29,French Guiana,France,125,1,93
99,2020-04-29,NaN,Madagascar,128,0,90
54,2020-04-29,NaN,Ethiopia,130,3,58
23,2020-04-29,NaN,Brunei,138,1,124
212,2020-04-29,Gansu,Mainland China,139,2,137
214,2020-04-29,Gibraltar,UK,141,0,131
219,2020-04-29,Guam,US,141,5,0
93,2020-04-29,NaN,Liberia,141,16,45
242,2020-04-29,Liaoning,Mainland China,146,2,143
222,2020-04-29,Guizhou,Mainland China,147,2,145
218,2020-04-29,Guadeloupe,France,149,12,82
26,2020-04-29,NaN,Burma,150,6,27
223,2020-04-29,Hainan,Mainland China,168,6,162
247,2020-04-29,Martinique,France,175,14,83
319,2020-04-29,Yunnan,Mainland China,185,2,181
207,2020-04-29,Faroe Islands,Denmark,187,0,181
304,2020-04-29,Tianjin,Mainland China,190,3,183
294,2020-04-29,Shanxi,Mainland China,197,0,164
234,2020-04-29,Inner Mongolia,Mainland China,200,1,150
67,2020-04-29,NaN,Guinea-Bissau,205,1,19
35,2020-04-29,NaN,Congo (Brazzaville),207,8,19
301,2020-04-29,Tasmania,Australia,219,12,144
135,2020-04-29,NaN,Rwanda,225,0,98
127,2020-04-29,NaN,Paraguay,239,9,102
221,2020-04-29,Guangxi,Mainland China,254,2,252
266,2020-04-29,Newfoundland and Labrador,Canada,258,3,0
175,2020-04-29,NaN,Vietnam,270,0,222
246,2020-04-29,Manitoba,Canada,275,6,0
58,2020-04-29,NaN,Gabon,276,3,67
102,2020-04-29,NaN,Maldives,278,1,17
291,2020-04-29,Shaanxi,Mainland China,306,3,253
236,2020-04-29,Isle of Man,UK,313,21,258
50,2020-04-29,NaN,Equatorial Guinea,315,1,9
111,2020-04-29,NaN,Montenegro,322,7,203
225,2020-04-29,Hebei,Mainland China,328,6,318
174,2020-04-29,NaN,Venezuela,331,10,142
106,2020-04-29,NaN,Mauritius,332,10,306
176,2020-04-29,NaN,West Bank and Gaza,344,2,71
182,2020-04-29,Alaska,US,355,9,0
211,2020-04-29,Fujian,Mainland China,355,1,353
155,2020-04-29,NaN,Sudan,375,28,32
49,2020-04-29,NaN,El Salvador,377,9,106
290,2020-04-29,Saskatchewan,Canada,383,6,0
86,2020-04-29,NaN,Kenya,384,15,129
82,2020-04-29,NaN,Jamaica,396,7,29
286,2020-04-29,Reunion,France,420,0,300
160,2020-04-29,NaN,Taiwan,429,6,311
297,2020-04-29,South Australia,Australia,438,4,420
84,2020-04-29,NaN,Jordan,451,8,356
255,2020-04-29,Montana,US,451,16,0
250,2020-04-29,Mayotte,France,460,4,235
104,2020-04-29,NaN,Malta,463,4,339
161,2020-04-29,NaN,Tanzania,480,16,167
103,2020-04-29,NaN,Mali,482,25,129
36,2020-04-29,NaN,Congo (Kinshasa),491,30,59
87,2020-04-29,NaN,Kosovo,510,12,93
60,2020-04-29,NaN,Georgia,517,6,178
197,2020-04-29,Channel Islands,UK,537,38,386
316,2020-04-29,Wyoming,US,545,7,0
314,2020-04-29,Western Australia,Australia,551,8,507
65,2020-04-29,NaN,Guatemala,557,16,62
295,2020-04-29,Sichuan,Mainland China,561,3,558
139,2020-04-29,NaN,San Marino,563,41,69
198,2020-04-29,Chongqing,Mainland China,579,6,573
149,2020-04-29,NaN,Somalia,582,28,20
190,2020-04-29,Beijing,Mainland China,593,9,542
224,2020-04-29,Hawaii,US,613,16,0
172,2020-04-29,NaN,Uruguay,630,15,412
25,2020-04-29,NaN,Burkina Faso,641,43,498
293,2020-04-29,Shanghai,Mainland China,647,7,597
154,2020-04-29,NaN,Sri Lanka,649,7,136
237,2020-04-29,Jiangsu,Mainland China,653,0,648
43,2020-04-29,NaN,Diamond Princess,712,13,645
119,2020-04-29,NaN,Niger,713,32,435
37,2020-04-29,NaN,Costa Rica,713,6,323
92,2020-04-29,NaN,Lebanon,721,24,150
89,2020-04-29,NaN,Kyrgyzstan,729,8,437
71,2020-04-29,NaN,Honduras,738,66,73
3,2020-04-29,NaN,Andorra,743,42,423
1,2020-04-29,NaN,Albania,766,30,455
292,2020-04-29,Shandong,Mainland China,787,7,772
40,2020-04-29,NaN,Cyprus,843,15,148
91,2020-04-29,NaN,Latvia,849,15,348
308,2020-04-29,Vermont,US,862,47,0
142,2020-04-29,NaN,Senegal,882,9,315
273,2020-04-29,Nova Scotia,Canada,935,28,0
238,2020-04-29,Jiangxi,Mainland China,937,1,936
226,2020-04-29,Heilongjiang,Mainland China,939,13,587
166,2020-04-29,NaN,Tunisia,980,40,294
185,2020-04-29,Anhui,Mainland China,991,6,985
230,2020-04-29,Hunan,Mainland China,1019,4,1015
283,2020-04-29,Queensland,Australia,1033,6,943
269,2020-04-29,North Dakota,US,1033,19,0
228,2020-04-29,Hong Kong,Hong Kong,1037,4,830
245,2020-04-29,Maine,US,1056,52,0
44,2020-04-29,NaN,Djibouti,1077,2,599
313,2020-04-29,West Virginia,US,1110,38,0
19,2020-04-29,NaN,Bolivia,1110,59,117
81,2020-04-29,NaN,Ivory Coast,1238,14,557
320,2020-04-29,Zhejiang,Mainland China,1268,1,1263
227,2020-04-29,Henan,Mainland China,1276,22,1254
66,2020-04-29,NaN,Guinea,1351,7,313
309,2020-04-29,Victoria,Australia,1361,18,1291
96,2020-04-29,NaN,Lithuania,1375,45,563
147,2020-04-29,NaN,Slovakia,1391,22,484
148,2020-04-29,NaN,Slovenia,1418,89,230
280,2020-04-29,Puerto Rico,US,1433,86,0
121,2020-04-29,NaN,North Macedonia,1442,73,627
24,2020-04-29,NaN,Bulgaria,1447,64,243
39,2020-04-29,NaN,Cuba,1467,58,617
117,2020-04-29,NaN,New Zealand,1476,19,1241
220,2020-04-29,Guangdong,Mainland China,1588,8,1557
52,2020-04-29,NaN,Estonia,1666,50,236
62,2020-04-29,NaN,Ghana,1671,16,188
20,2020-04-29,NaN,Bosnia and Herzegovina,1677,65,710
120,2020-04-29,NaN,Nigeria,1728,51,307
9,2020-04-29,NaN,Azerbaijan,1766,23,1267
73,2020-04-29,NaN,Iceland,1797,10,1656
30,2020-04-29,NaN,Cameroon,1832,61,934
7,2020-04-29,NaN,Armenia,1932,30,900
0,2020-04-29,NaN,Afghanistan,1939,60,252
231,2020-04-29,Idaho,US,1952,60,0
173,2020-04-29,NaN,Uzbekistan,2002,9,1096
77,2020-04-29,NaN,Iraq,2003,92,1346
261,2020-04-29,New Hampshire,US,2058,60,0
38,2020-04-29,NaN,Croatia,2062,67,1288
193,2020-04-29,British Columbia,Canada,2087,109,0
123,2020-04-29,NaN,Oman,2274,10,364
299,2020-04-29,South Dakota,US,2373,13,0
277,2020-04-29,Oregon,US,2446,101,0
63,2020-04-29,NaN,Greece,2576,139,577
72,2020-04-29,NaN,Hungary,2727,300,536
11,2020-04-29,NaN,Bahrain,2921,8,1455
162,2020-04-29,NaN,Thailand,2947,54,2665
264,2020-04-29,New South Wales,Australia,3016,40,2284
85,2020-04-29,NaN,Kazakhstan,3138,25,819
187,2020-04-29,Arkansas,US,3193,57,0
263,2020-04-29,New Mexico,US,3213,112,0
275,2020-04-29,Oklahoma,US,3473,214,0
88,2020-04-29,NaN,Kuwait,3740,24,1389
97,2020-04-29,NaN,Luxembourg,3769,89,3134
108,2020-04-29,NaN,Moldova,3771,111,1114
240,2020-04-29,Kansas,US,3839,134,0
2,2020-04-29,NaN,Algeria,3848,444,1702
257,2020-04-29,Nebraska,US,3851,56,0
205,2020-04-29,District of Columbia,US,4106,205,0
6,2020-04-29,NaN,Argentina,4285,214,1192
112,2020-04-29,NaN,Morocco,4321,168,928
307,2020-04-29,Utah,US,4497,45,0
241,2020-04-29,Kentucky,US,4537,234,0
252,2020-04-29,Minnesota,US,4644,319,0
202,2020-04-29,Delaware,US,4655,144,0
56,2020-04-29,NaN,Finland,4906,206,2800
258,2020-04-29,Nevada,US,4934,230,0
183,2020-04-29,Alberta,Canada,5165,87,0
48,2020-04-29,NaN,Egypt,5268,380,1335
150,2020-04-29,NaN,South Africa,5350,103,2073
298,2020-04-29,South Carolina,US,5882,231,0
101,2020-04-29,NaN,Malaysia,5945,100,4087
34,2020-04-29,NaN,Colombia,6207,278,1411
125,2020-04-29,NaN,Panama,6378,178,527
315,2020-04-29,Wisconsin,US,6520,308,0
253,2020-04-29,Mississippi,US,6569,250,0
143,2020-04-29,NaN,Serbia,6630,125,870
46,2020-04-29,NaN,Dominican Republic,6652,293,1228
235,2020-04-29,Iowa,US,6843,148,0
181,2020-04-29,Alabama,US,6912,256,0
12,2020-04-29,NaN,Bangladesh,7103,163,150
186,2020-04-29,Arizona,US,7209,308,0
41,2020-04-29,NaN,Czech Republic,7579,227,3108
254,2020-04-29,Missouri,US,7660,338,0
122,2020-04-29,NaN,Norway,7710,207,32
129,2020-04-29,NaN,Philippines,8212,558,1023
287,2020-04-29,Rhode Island,US,8247,251,0
42,2020-04-29,NaN,Denmark,9008,443,6366
75,2020-04-29,NaN,Indonesia,9771,784,1391
170,2020-04-29,NaN,Ukraine,9866,250,1103
268,2020-04-29,North Carolina,US,10180,382,0
302,2020-04-29,Tennessee,US,10366,195,0
151,2020-04-29,NaN,South Korea,10765,247,9059
171,2020-04-29,NaN,United Arab Emirates,11929,98,2329
133,2020-04-29,NaN,Romania,11978,693,3569
132,2020-04-29,NaN,Qatar,12564,10,1243
130,2020-04-29,NaN,Poland,12640,624,3025
14,2020-04-29,NaN,Belarus,13181,84,2072
83,2020-04-29,NaN,Japan,13895,413,2368
312,2020-04-29,Washington,US,14070,801,0
199,2020-04-29,Colorado,US,14758,766,0
33,2020-04-29,NaN,Chile,14885,216,8057
311,2020-04-29,Virginia,US,14962,522,0
8,2020-04-29,NaN,Austria,15402,580,12779
124,2020-04-29,NaN,Pakistan,15525,343,3425
146,2020-04-29,NaN,Singapore,15641,14,1188
79,2020-04-29,NaN,Israel,15834,215,8233
276,2020-04-29,Ontario,Canada,16978,1153,0
233,2020-04-29,Indiana,US,17182,964,0
274,2020-04-29,Ohio,US,17303,937,0
107,2020-04-29,NaN,Mexico,17799,1732,11423
78,2020-04-29,NaN,Ireland,20253,1190,13386
157,2020-04-29,NaN,Sweden,20302,2462,1005
248,2020-04-29,Maryland,US,20849,1078,0
141,2020-04-29,NaN,Saudi Arabia,21402,157,2953
131,2020-04-29,NaN,Portugal,24505,973,1470
47,2020-04-29,NaN,Ecuador,24675,883,1557
213,2020-04-29,Georgia,US,25775,1101,0
282,2020-04-29,Quebec,Canada,26610,1762,0
200,2020-04-29,Connecticut,US,26767,2169,0
303,2020-04-29,Texas,US,27257,754,0
243,2020-04-29,Louisiana,US,27660,1845,0
158,2020-04-29,NaN,Switzerland,29407,1716,22600
74,2020-04-29,NaN,India,33062,1079,8437
208,2020-04-29,Florida,US,33193,1218,0
128,2020-04-29,NaN,Peru,33931,943,10037
116,2020-04-29,NaN,Netherlands,38802,4711,0
251,2020-04-29,Michigan,US,40399,3670,0
278,2020-04-29,Pennsylvania,US,46327,2373,0
15,2020-04-29,NaN,Belgium,47859,7501,11283
195,2020-04-29,California,US,48747,1946,0
232,2020-04-29,Illinois,US,50358,2215,0
249,2020-04-29,Massachusetts,US,60265,3405,0
229,2020-04-29,Hubei,Mainland China,68128,4512,63616
22,2020-04-29,NaN,Brazil,79685,5513,34132
76,2020-04-29,NaN,Iran,93657,5957,73791
134,2020-04-29,NaN,Russia,99399,972,10286
262,2020-04-29,New Jersey,US,116365,6771,0
167,2020-04-29,NaN,Turkey,117589,3081,44040
61,2020-04-29,NaN,Germany,161539,6467,120400
57,2020-04-29,NaN,France,165093,24087,48228
168,2020-04-29,NaN,UK,165221,26097,0
80,2020-04-29,NaN,Italy,203591,27682,71252
153,2020-04-29,NaN,Spain,236899,24275,132929
265,2020-04-29,New York,US,299691,23477,0

# Q. 6-B ) Sort the entire data wrt No. of Recovered cases in descending order.

In [25]:
df.sort_values(by='Recovered',ascending=False)

,Date,State,Region,Confirmed,Deaths,Recovered
153,2020-04-29,NaN,Spain,236899,24275,132929
61,2020-04-29,NaN,Germany,161539,6467,120400
76,2020-04-29,NaN,Iran,93657,5957,73791
80,2020-04-29,NaN,Italy,203591,27682,71252
229,2020-04-29,Hubei,Mainland China,68128,4512,63616
57,2020-04-29,NaN,France,165093,24087,48228
167,2020-04-29,NaN,Turkey,117589,3081,44040
22,2020-04-29,NaN,Brazil,79685,5513,34132
158,2020-04-29,NaN,Switzerland,29407,1716,22600
78,2020-04-29,NaN,Ireland,20253,1190,13386
8,2020-04-29,NaN,Austria,15402,580,12779
107,2020-04-29,NaN,Mexico,17799,1732,11423
15,2020-04-29,NaN,Belgium,47859,7501,11283
134,2020-04-29,NaN,Russia,99399,972,10286
128,2020-04-29,NaN,Peru,33931,943,10037
151,2020-04-29,NaN,South Korea,10765,247,9059
74,2020-04-29,NaN,India,33062,1079,8437
79,2020-04-29,NaN,Israel,15834,215,8233
33,2020-04-29,NaN,Chile,14885,216,8057
42,2020-04-29,NaN,Denmark,9008,443,6366
101,2020-04-29,NaN,Malaysia,5945,100,4087
133,2020-04-29,NaN,Romania,11978,693,3569
124,2020-04-29,NaN,Pakistan,15525,343,3425
97,2020-04-29,NaN,Luxembourg,3769,89,3134
41,2020-04-29,NaN,Czech Republic,7579,227,3108
130,2020-04-29,NaN,Poland,12640,624,3025
141,2020-04-29,NaN,Saudi Arabia,21402,157,2953
56,2020-04-29,NaN,Finland,4906,206,2800
162,2020-04-29,NaN,Thailand,2947,54,2665
83,2020-04-29,NaN,Japan,13895,413,2368
171,2020-04-29,NaN,United Arab Emirates,11929,98,2329
264,2020-04-29,New South Wales,Australia,3016,40,2284
150,2020-04-29,NaN,South Africa,5350,103,2073
14,2020-04-29,NaN,Belarus,13181,84,2072
2,2020-04-29,NaN,Algeria,3848,444,1702
73,2020-04-29,NaN,Iceland,1797,10,1656
47,2020-04-29,NaN,Ecuador,24675,883,1557
220,2020-04-29,Guangdong,Mainland China,1588,8,1557
131,2020-04-29,NaN,Portugal,24505,973,1470
11,2020-04-29,NaN,Bahrain,2921,8,1455
34,2020-04-29,NaN,Colombia,6207,278,1411
75,2020-04-29,NaN,Indonesia,9771,784,1391
88,2020-04-29,NaN,Kuwait,3740,24,1389
77,2020-04-29,NaN,Iraq,2003,92,1346
48,2020-04-29,NaN,Egypt,5268,380,1335
309,2020-04-29,Victoria,Australia,1361,18,1291
38,2020-04-29,NaN,Croatia,2062,67,1288
9,2020-04-29,NaN,Azerbaijan,1766,23,1267
320,2020-04-29,Zhejiang,Mainland China,1268,1,1263
227,2020-04-29,Henan,Mainland China,1276,22,1254
132,2020-04-29,NaN,Qatar,12564,10,1243
117,2020-04-29,NaN,New Zealand,1476,19,1241
46,2020-04-29,NaN,Dominican Republic,6652,293,1228
6,2020-04-29,NaN,Argentina,4285,214,1192
146,2020-04-29,NaN,Singapore,15641,14,1188
108,2020-04-29,NaN,Moldova,3771,111,1114
170,2020-04-29,NaN,Ukraine,9866,250,1103
173,2020-04-29,NaN,Uzbekistan,2002,9,1096
129,2020-04-29,NaN,Philippines,8212,558,1023
230,2020-04-29,Hunan,Mainland China,1019,4,1015
157,2020-04-29,NaN,Sweden,20302,2462,1005
185,2020-04-29,Anhui,Mainland China,991,6,985
283,2020-04-29,Queensland,Australia,1033,6,943
238,2020-04-29,Jiangxi,Mainland China,937,1,936
30,2020-04-29,NaN,Cameroon,1832,61,934
112,2020-04-29,NaN,Morocco,4321,168,928
7,2020-04-29,NaN,Armenia,1932,30,900
143,2020-04-29,NaN,Serbia,6630,125,870
228,2020-04-29,Hong Kong,Hong Kong,1037,4,830
85,2020-04-29,NaN,Kazakhstan,3138,25,819
292,2020-04-29,Shandong,Mainland China,787,7,772
20,2020-04-29,NaN,Bosnia and Herzegovina,1677,65,710
237,2020-04-29,Jiangsu,Mainland China,653,0,648
43,2020-04-29,NaN,Diamond Princess,712,13,645
121,2020-04-29,NaN,North Macedonia,1442,73,627
39,2020-04-29,NaN,Cuba,1467,58,617
44,2020-04-29,NaN,Djibouti,1077,2,599
293,2020-04-29,Shanghai,Mainland China,647,7,597
226,2020-04-29,Heilongjiang,Mainland China,939,13,587
63,2020-04-29,NaN,Greece,2576,139,577
198,2020-04-29,Chongqing,Mainland China,579,6,573
96,2020-04-29,NaN,Lithuania,1375,45,563
295,2020-04-29,Sichuan,Mainland China,561,3,558
81,2020-04-29,NaN,Ivory Coast,1238,14,557
190,2020-04-29,Beijing,Mainland China,593,9,542
72,2020-04-29,NaN,Hungary,2727,300,536
125,2020-04-29,NaN,Panama,6378,178,527
314,2020-04-29,Western Australia,Australia,551,8,507
25,2020-04-29,NaN,Burkina Faso,641,43,498
147,2020-04-29,NaN,Slovakia,1391,22,484
1,2020-04-29,NaN,Albania,766,30,455
89,2020-04-29,NaN,Kyrgyzstan,729,8,437
119,2020-04-29,NaN,Niger,713,32,435
3,2020-04-29,NaN,Andorra,743,42,423
297,2020-04-29,South Australia,Australia,438,4,420
172,2020-04-29,NaN,Uruguay,630,15,412
197,2020-04-29,Channel Islands,UK,537,38,386
123,2020-04-29,NaN,Oman,2274,10,364
84,2020-04-29,NaN,Jordan,451,8,356
211,2020-04-29,Fujian,Mainland China,355,1,353
91,2020-04-29,NaN,Latvia,849,15,348
104,2020-04-29,NaN,Malta,463,4,339
37,2020-04-29,NaN,Costa Rica,713,6,323
225,2020-04-29,Hebei,Mainland China,328,6,318
142,2020-04-29,NaN,Senegal,882,9,315
66,2020-04-29,NaN,Guinea,1351,7,313
160,2020-04-29,NaN,Taiwan,429,6,311
120,2020-04-29,NaN,Nigeria,1728,51,307
106,2020-04-29,NaN,Mauritius,332,10,306
286,2020-04-29,Reunion,France,420,0,300
166,2020-04-29,NaN,Tunisia,980,40,294
236,2020-04-29,Isle of Man,UK,313,21,258
291,2020-04-29,Shaanxi,Mainland China,306,3,253
221,2020-04-29,Guangxi,Mainland China,254,2,252
0,2020-04-29,NaN,Afghanistan,1939,60,252
24,2020-04-29,NaN,Bulgaria,1447,64,243
52,2020-04-29,NaN,Estonia,1666,50,236
250,2020-04-29,Mayotte,France,460,4,235
148,2020-04-29,NaN,Slovenia,1418,89,230
175,2020-04-29,NaN,Vietnam,270,0,222
111,2020-04-29,NaN,Montenegro,322,7,203
62,2020-04-29,NaN,Ghana,1671,16,188
304,2020-04-29,Tianjin,Mainland China,190,3,183
319,2020-04-29,Yunnan,Mainland China,185,2,181
207,2020-04-29,Faroe Islands,Denmark,187,0,181
60,2020-04-29,NaN,Georgia,517,6,178
161,2020-04-29,NaN,Tanzania,480,16,167
294,2020-04-29,Shanxi,Mainland China,197,0,164
223,2020-04-29,Hainan,Mainland China,168,6,162
234,2020-04-29,Inner Mongolia,Mainland China,200,1,150
92,2020-04-29,NaN,Lebanon,721,24,150
12,2020-04-29,NaN,Bangladesh,7103,163,150
40,2020-04-29,NaN,Cyprus,843,15,148
222,2020-04-29,Guizhou,Mainland China,147,2,145
301,2020-04-29,Tasmania,Australia,219,12,144
242,2020-04-29,Liaoning,Mainland China,146,2,143
174,2020-04-29,NaN,Venezuela,331,10,142
212,2020-04-29,Gansu,Mainland China,139,2,137
154,2020-04-29,NaN,Sri Lanka,649,7,136
214,2020-04-29,Gibraltar,UK,141,0,131
103,2020-04-29,NaN,Mali,482,25,129
86,2020-04-29,NaN,Kenya,384,15,129
23,2020-04-29,NaN,Brunei,138,1,124
29,2020-04-29,NaN,Cambodia,122,0,119
19,2020-04-29,NaN,Bolivia,1110,59,117
49,2020-04-29,NaN,El Salvador,377,9,106
127,2020-04-29,NaN,Paraguay,239,9,102
189,2020-04-29,Australian Capital Territory,Australia,106,3,101
239,2020-04-29,Jilin,Mainland China,111,1,99
135,2020-04-29,NaN,Rwanda,225,0,98
87,2020-04-29,NaN,Kosovo,510,12,93
209,2020-04-29,French Guiana,France,125,1,93
99,2020-04-29,NaN,Madagascar,128,0,90
247,2020-04-29,Martinique,France,175,14,83
218,2020-04-29,Guadeloupe,France,149,12,82
267,2020-04-29,Ningxia,Mainland China,75,0,75
71,2020-04-29,NaN,Honduras,738,66,73
317,2020-04-29,Xinjiang,Mainland China,76,3,73
188,2020-04-29,Aruba,Netherlands,100,2,73
176,2020-04-29,NaN,West Bank and Gaza,344,2,71
165,2020-04-29,NaN,Trinidad and Tobago,116,8,71
139,2020-04-29,NaN,San Marino,563,41,69
58,2020-04-29,NaN,Gabon,276,3,67
164,2020-04-29,NaN,Togo,109,7,64
65,2020-04-29,NaN,Guatemala,557,16,62
36,2020-04-29,NaN,Congo (Kinshasa),491,30,59
54,2020-04-29,NaN,Ethiopia,130,3,58
109,2020-04-29,NaN,Monaco,95,4,58
95,2020-04-29,NaN,Liechtenstein,82,1,55
179,2020-04-29,NaN,Zambia,97,3,54
169,2020-04-29,NaN,Uganda,81,0,52
210,2020-04-29,French Polynesia,France,58,0,50
191,2020-04-29,Bermuda,UK,111,6,48
93,2020-04-29,NaN,Liberia,141,16,45
13,2020-04-29,NaN,Barbados,80,7,39
244,2020-04-29,Macau,Macau,45,0,34
296,2020-04-29,Sint Maarten,Netherlands,75,13,33
17,2020-04-29,NaN,Benin,64,1,33
122,2020-04-29,NaN,Norway,7710,207,32
155,2020-04-29,NaN,Sudan,375,28,32
82,2020-04-29,NaN,Jamaica,396,7,29
26,2020-04-29,NaN,Burma,150,6,27
271,2020-04-29,Northern Territory,Australia,28,0,25
300,2020-04-29,St Martin,France,38,3,24
10,2020-04-29,NaN,Bahamas,80,11,23
159,2020-04-29,NaN,Syria,43,3,21
149,2020-04-29,NaN,Somalia,582,28,20
51,2020-04-29,NaN,Eritrea,39,0,19
32,2020-04-29,NaN,Chad,52,2,19
67,2020-04-29,NaN,Guinea-Bissau,205,1,19
35,2020-04-29,NaN,Congo (Brazzaville),207,8,19
281,2020-04-29,Qinghai,Mainland China,18,0,18
94,2020-04-29,NaN,Libya,61,2,18
68,2020-04-29,NaN,Guyana,78,8,18
102,2020-04-29,NaN,Maldives,278,1,17
260,2020-04-29,New Caledonia,France,18,0,17
115,2020-04-29,NaN,Nepal,57,0,16
137,2020-04-29,NaN,Saint Lucia,17,0,15
201,2020-04-29,Curacao,Netherlands,16,1,13
64,2020-04-29,NaN,Grenada,20,0,13
45,2020-04-29,NaN,Dominica,16,0,13
55,2020-04-29,NaN,Fiji,18,0,12
145,2020-04-29,NaN,Sierra Leone,104,4,12
113,2020-04-29,NaN,Mozambique,76,0,12
217,2020-04-29,Greenland,Denmark,11,0,11
5,2020-04-29,NaN,Antigua and Barbuda,24,3,11
206,2020-04-29,Falkland Islands (Malvinas),UK,13,0,11
110,2020-04-29,NaN,Mongolia,38,0,10
31,2020-04-29,NaN,Central African Republic,50,0,10
196,2020-04-29,Cayman Islands,UK,73,1,10
53,2020-04-29,NaN,Eswatini,91,1,10
50,2020-04-29,NaN,Equatorial Guinea,315,1,9
16,2020-04-29,NaN,Belize,18,2,9
69,2020-04-29,NaN,Haiti,76,6,8
59,2020-04-29,NaN,Gambia,10,1,8
156,2020-04-29,NaN,Suriname,10,1,8
114,2020-04-29,NaN,Namibia,16,0,8
138,2020-04-29,NaN,Saint Vincent and the Grenadines,16,0,8
4,2020-04-29,NaN,Angola,27,2,7
118,2020-04-29,NaN,Nicaragua,13,3,7
100,2020-04-29,NaN,Malawi,36,3,7
90,2020-04-29,NaN,Laos,19,0,7
163,2020-04-29,NaN,Timor-Leste,24,0,6
144,2020-04-29,NaN,Seychelles,11,0,6
180,2020-04-29,NaN,Zimbabwe,32,4,5
21,2020-04-29,NaN,Botswana,23,1,5
306,2020-04-29,Turks and Caicos Islands,UK,12,1,5
136,2020-04-29,NaN,Saint Kitts and Nevis,15,0,4
27,2020-04-29,NaN,Burundi,11,1,4
28,2020-04-29,NaN,Cabo Verde,114,1,2
256,2020-04-29,Montserrat,UK,11,1,2
70,2020-04-29,NaN,Holy See,10,0,2
186,2020-04-29,Arizona,US,7209,308,0
181,2020-04-29,Alabama,US,6912,256,0
182,2020-04-29,Alaska,US,355,9,0
183,2020-04-29,Alberta,Canada,5165,87,0
277,2020-04-29,Oregon,US,2446,101,0
280,2020-04-29,Puerto Rico,US,1433,86,0
193,2020-04-29,British Columbia,Canada,2087,109,0
278,2020-04-29,Pennsylvania,US,46327,2373,0
287,2020-04-29,Rhode Island,US,8247,251,0
187,2020-04-29,Arkansas,US,3193,57,0
279,2020-04-29,Prince Edward Island,Canada,27,0,0
282,2020-04-29,Quebec,Canada,26610,1762,0
290,2020-04-29,Saskatchewan,Canada,383,6,0
299,2020-04-29,South Dakota,US,2373,13,0
168,2020-04-29,NaN,UK,165221,26097,0
298,2020-04-29,South Carolina,US,5882,231,0
275,2020-04-29,Oklahoma,US,3473,214,0
302,2020-04-29,Tennessee,US,10366,195,0
303,2020-04-29,Texas,US,27257,754,0
152,2020-04-29,NaN,South Sudan,34,0,0
307,2020-04-29,Utah,US,4497,45,0
308,2020-04-29,Vermont,US,862,47,0
310,2020-04-29,Virgin Islands,US,57,4,0
311,2020-04-29,Virginia,US,14962,522,0
312,2020-04-29,Washington,US,14070,801,0
313,2020-04-29,West Virginia,US,1110,38,0
315,2020-04-29,Wisconsin,US,6520,308,0
316,2020-04-29,Wyoming,US,545,7,0
318,2020-04-29,Yukon,Canada,11,0,0
276,2020-04-29,Ontario,Canada,16978,1153,0
231,2020-04-29,Idaho,US,1952,60,0
232,2020-04-29,Illinois,US,50358,2215,0
251,2020-04-29,Michigan,US,40399,3670,0
249,2020-04-29,Massachusetts,US,60265,3405,0
248,2020-04-29,Maryland,US,20849,1078,0
205,2020-04-29,District of Columbia,US,4106,205,0
246,2020-04-29,Manitoba,Canada,275,6,0
245,2020-04-29,Maine,US,1056,52,0
208,2020-04-29,Florida,US,33193,1218,0
243,2020-04-29,Louisiana,US,27660,1845,0
213,2020-04-29,Georgia,US,25775,1101,0
241,2020-04-29,Kentucky,US,4537,234,0
240,2020-04-29,Kansas,US,3839,134,0
215,2020-04-29,Grand Princess,Canada,13,0,0
216,2020-04-29,Grand Princess,US,103,3,0
219,2020-04-29,Guam,US,141,5,0
116,2020-04-29,NaN,Netherlands,38802,4711,0
235,2020-04-29,Iowa,US,6843,148,0
224,2020-04-29,Hawaii,US,613,16,0
233,2020-04-29,Indiana,US,17182,964,0
204,2020-04-29,Diamond Princess cruise ship,US,49,0,0
252,2020-04-29,Minnesota,US,4644,319,0
273,2020-04-29,Nova Scotia,Canada,935,28,0
253,2020-04-29,Mississippi,US,6569,250,0
195,2020-04-29,California,US,48747,1946,0
270,2020-04-29,Northern Mariana Islands,US,14,2,0
269,2020-04-29,North Dakota,US,1033,19,0
268,2020-04-29,North Carolina,US,10180,382,0
199,2020-04-29,Colorado,US,14758,766,0
266,2020-04-29,Newfoundland and Labrador,Canada,258,3,0
265,2020-04-29,New York,US,299691,23477,0
200,2020-04-29,Connecticut,US,26767,2169,0
263,2020-04-29,New Mexico,US,3213,112,0
262,2020-04-29,New Jersey,US,116365,6771,0
261,2020-04-29,New Hampshire,US,2058,60,0
202,2020-04-29,Delaware,US,4655,144,0
259,2020-04-29,New Brunswick,Canada,118,0,0
258,2020-04-29,Nevada,US,4934,230,0
257,2020-04-29,Nebraska,US,3851,56,0
255,2020-04-29,Montana,US,451,16,0
254,2020-04-29,Missouri,US,7660,338,0
274,2020-04-29,Ohio,US,17303,937,0